### ISSUE TITLE
Client.lua attempts to index nil value (local "props") on lines 185 and 186

### ISSUE THREAD

**Issue by Insaneshane99** [ArcadiaRoleplay/qb-luckywheel#1]
Ignore the qb-casino error ive fixed it already

![rp server errors](https://user-images.githubusercontent.com/87678580/130117581-7e0c809b-9e2b-495e-8462-b4bc1961af1e.PNG)
![car win2](https://user-images.githubusercontent.com/87678580/130118257-16edcb06-e79c-4e6f-96e0-08e8ba5bc638.PNG)

any help on fixing this is greatly apreciated.

**Comment by Nathan-FiveM** [comment]
You don't have the rcf in your shared.

**Comment by Insaneshane99** [comment]
Ive added this to my Qb-core shared.lua file but still get the same error. 
![image](https://user-images.githubusercontent.com/87678580/130192461-ee89a9b0-bb5a-4396-9c3e-2cb0d49fe611.png)
 Could you manybe provide the required shared file contents?

**Comment by Nathan-FiveM** [comment]
change the code QBCore.Functions.SpawnVehicle("rcf", function(veh)

to QBCore.Functions.SpawnVehicle("vectre", function(veh)

If not this may be due to me using the outdated core when I originally made this, I'll take a look

**Comment by Nathan-FiveM** [comment]
I'm a dumbass, the local hash = props.model isn't needed

**Comment by Insaneshane99** [comment]
thank you sir that appears to have fixed it
